// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.SpellingBeeGenerator
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("centerLetter")]
        public string CenterLetter { get; set; }

        [JsonProperty("outerLetters")]
        public string[] OuterLetters { get; set; }

        [JsonProperty("allLetters")]
        public string[] AllLetters { get; set; }

        [JsonProperty("difficulty")]
        public string Difficulty { get; set; }

        [JsonProperty("wordCount")]
        public long WordCount { get; set; }

        [JsonProperty("pangramCount")]
        public long PangramCount { get; set; }

        [JsonProperty("maxPoints")]
        public long MaxPoints { get; set; }

        [JsonProperty("words")]
        public Word[] Words { get; set; }

        [JsonProperty("html")]
        public string Html { get; set; }

        [JsonProperty("image")]
        public Image Image { get; set; }
    }

    public partial class Image
    {
        [JsonProperty("imageName")]
        public string ImageName { get; set; }

        [JsonProperty("format")]
        public string Format { get; set; }

        [JsonProperty("downloadURL")]
        public Uri DownloadUrl { get; set; }

        [JsonProperty("expires")]
        public long Expires { get; set; }
    }

    public partial class Word
    {
        [JsonProperty("word")]
        public string WordWord { get; set; }

        [JsonProperty("points")]
        public long Points { get; set; }

        [JsonProperty("isPangram")]
        public bool IsPangram { get; set; }
    }
}
